FROM nginx:alpine

RUN rm -rf /var/cache/apk/* \
    && mkdir -p /etc/nginx/conf.d \
    && mkdir -p /run/nginx

COPY ./load-balancer/nginx.conf /etc/nginx/nginx.conf
COPY ./load-balancer/server.conf /etc/nginx/conf.d/server.conf
COPY ./load-balancer/run.sh /usr/bin/run

RUN chmod +x /usr/bin/run

CMD run
