// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tasks.proto

package tasks

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Done                 bool     `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// ///////////////////////////////////////////////////
// REQUESTS
// ///////////////////////////////////////////////////
type CommonRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRequest) Reset()         { *m = CommonRequest{} }
func (m *CommonRequest) String() string { return proto.CompactTextString(m) }
func (*CommonRequest) ProtoMessage()    {}
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{1}
}
func (m *CommonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRequest.Unmarshal(m, b)
}
func (m *CommonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRequest.Marshal(b, m, deterministic)
}
func (dst *CommonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRequest.Merge(dst, src)
}
func (m *CommonRequest) XXX_Size() int {
	return xxx_messageInfo_CommonRequest.Size(m)
}
func (m *CommonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRequest proto.InternalMessageInfo

func (m *CommonRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTasksRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	IsOpen               bool     `protobuf:"varint,3,opt,name=isOpen,proto3" json:"isOpen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksRequest) Reset()         { *m = GetTasksRequest{} }
func (m *GetTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetTasksRequest) ProtoMessage()    {}
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{2}
}
func (m *GetTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksRequest.Unmarshal(m, b)
}
func (m *GetTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksRequest.Marshal(b, m, deterministic)
}
func (dst *GetTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksRequest.Merge(dst, src)
}
func (m *GetTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetTasksRequest.Size(m)
}
func (m *GetTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksRequest proto.InternalMessageInfo

func (m *GetTasksRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTasksRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetTasksRequest) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

type CreateTaskRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{3}
}
func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(dst, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTaskRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateTaskRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Done                 bool     `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{4}
}
func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(dst, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTaskRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateTaskRequest) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

// //////////////////////////////////////////////////////
// RESPONSES
// ///////////////////////////////////////////////////
type CommonResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{5}
}
func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (dst *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(dst, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CommonResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskResponse) Reset()         { *m = GetTaskResponse{} }
func (m *GetTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskResponse) ProtoMessage()    {}
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{6}
}
func (m *GetTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskResponse.Unmarshal(m, b)
}
func (m *GetTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskResponse.Marshal(b, m, deterministic)
}
func (dst *GetTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskResponse.Merge(dst, src)
}
func (m *GetTaskResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskResponse.Size(m)
}
func (m *GetTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskResponse proto.InternalMessageInfo

func (m *GetTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetTasksResponse struct {
	Tasks                []*Task                    `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Next                 *GetTasksResponse_ListNode `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Prev                 *GetTasksResponse_ListNode `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetTasksResponse) Reset()         { *m = GetTasksResponse{} }
func (m *GetTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetTasksResponse) ProtoMessage()    {}
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{7}
}
func (m *GetTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksResponse.Unmarshal(m, b)
}
func (m *GetTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksResponse.Marshal(b, m, deterministic)
}
func (dst *GetTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksResponse.Merge(dst, src)
}
func (m *GetTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetTasksResponse.Size(m)
}
func (m *GetTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksResponse proto.InternalMessageInfo

func (m *GetTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GetTasksResponse) GetNext() *GetTasksResponse_ListNode {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *GetTasksResponse) GetPrev() *GetTasksResponse_ListNode {
	if m != nil {
		return m.Prev
	}
	return nil
}

type GetTasksResponse_ListNode struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksResponse_ListNode) Reset()         { *m = GetTasksResponse_ListNode{} }
func (m *GetTasksResponse_ListNode) String() string { return proto.CompactTextString(m) }
func (*GetTasksResponse_ListNode) ProtoMessage()    {}
func (*GetTasksResponse_ListNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_tasks_75cad3593992d9ef, []int{7, 0}
}
func (m *GetTasksResponse_ListNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksResponse_ListNode.Unmarshal(m, b)
}
func (m *GetTasksResponse_ListNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksResponse_ListNode.Marshal(b, m, deterministic)
}
func (dst *GetTasksResponse_ListNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksResponse_ListNode.Merge(dst, src)
}
func (m *GetTasksResponse_ListNode) XXX_Size() int {
	return xxx_messageInfo_GetTasksResponse_ListNode.Size(m)
}
func (m *GetTasksResponse_ListNode) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksResponse_ListNode.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksResponse_ListNode proto.InternalMessageInfo

func (m *GetTasksResponse_ListNode) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTasksResponse_ListNode) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*CommonRequest)(nil), "CommonRequest")
	proto.RegisterType((*GetTasksRequest)(nil), "GetTasksRequest")
	proto.RegisterType((*CreateTaskRequest)(nil), "CreateTaskRequest")
	proto.RegisterType((*UpdateTaskRequest)(nil), "UpdateTaskRequest")
	proto.RegisterType((*CommonResponse)(nil), "CommonResponse")
	proto.RegisterType((*GetTaskResponse)(nil), "GetTaskResponse")
	proto.RegisterType((*GetTasksResponse)(nil), "GetTasksResponse")
	proto.RegisterType((*GetTasksResponse_ListNode)(nil), "GetTasksResponse.ListNode")
}

func init() { proto.RegisterFile("tasks.proto", fileDescriptor_tasks_75cad3593992d9ef) }

var fileDescriptor_tasks_75cad3593992d9ef = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0xa4, 0xc9, 0x52, 0x26, 0xda, 0x6e, 0x6b, 0x21, 0x14, 0xc2, 0x81, 0xc8, 0xa7, 0x1e,
	0x90, 0x91, 0xba, 0x07, 0x38, 0x71, 0x29, 0xd2, 0x0a, 0x09, 0x81, 0x14, 0x81, 0xb8, 0x12, 0xd6,
	0xb3, 0xc8, 0xda, 0x26, 0x0e, 0xb1, 0x41, 0xfc, 0x45, 0xfe, 0x14, 0x42, 0x9e, 0x7c, 0xd1, 0xa4,
	0x15, 0xdb, 0x9b, 0x67, 0xf2, 0xe6, 0xcd, 0xcc, 0xf3, 0x73, 0x20, 0xb2, 0xb9, 0xb9, 0x33, 0xa2,
	0xaa, 0xb5, 0xd5, 0xfc, 0x0b, 0x04, 0x1f, 0x73, 0x73, 0xc7, 0x16, 0xe0, 0x2b, 0x19, 0x7b, 0xa9,
	0xb7, 0x0e, 0x33, 0x5f, 0x49, 0xc6, 0x20, 0x90, 0xba, 0xc4, 0xd8, 0x4f, 0xbd, 0xf5, 0x3c, 0xa3,
	0xb3, 0xcb, 0x95, 0x79, 0x81, 0xf1, 0x2c, 0xf5, 0xd6, 0x0f, 0x33, 0x3a, 0xb3, 0x14, 0x22, 0x89,
	0xe6, 0xa6, 0x56, 0x95, 0x55, 0xba, 0x8c, 0x03, 0xfa, 0xf4, 0x6f, 0x8a, 0x3f, 0x83, 0x8b, 0xad,
	0x2e, 0x0a, 0x5d, 0x66, 0xf8, 0xfd, 0x07, 0x1a, 0x3b, 0x6e, 0xc5, 0x3f, 0xc3, 0xe5, 0x35, 0x5a,
	0x37, 0x85, 0xe9, 0x20, 0x8f, 0x20, 0xdc, 0xa9, 0x42, 0xd9, 0x16, 0xd5, 0x04, 0xec, 0x31, 0x9c,
	0xeb, 0xdb, 0x5b, 0x83, 0x96, 0xa6, 0x0a, 0xb3, 0x36, 0x72, 0x79, 0x65, 0x3e, 0x54, 0x58, 0xd2,
	0x64, 0xf3, 0xac, 0x8d, 0xf8, 0x5b, 0x58, 0x6d, 0x6b, 0xcc, 0x2d, 0x3a, 0xee, 0x8e, 0xba, 0x5b,
	0xc2, 0x3b, 0xbe, 0x84, 0x3f, 0x5d, 0xa2, 0x80, 0xd5, 0xa7, 0x4a, 0x8e, 0xa8, 0x0e, 0x68, 0x46,
	0xd4, 0xfe, 0x71, 0xea, 0xd9, 0x84, 0xba, 0x57, 0x3a, 0x18, 0x94, 0xe6, 0xaf, 0x61, 0xd1, 0x69,
	0x66, 0x2a, 0x5d, 0x1a, 0xd2, 0xfe, 0x46, 0xcb, 0x7e, 0x6c, 0x77, 0x66, 0x31, 0x3c, 0x28, 0xd0,
	0x98, 0xfc, 0x5b, 0xd7, 0xb2, 0x0b, 0xf9, 0xf3, 0x5e, 0xd2, 0x9e, 0xe0, 0x09, 0x04, 0xee, 0xde,
	0x89, 0x20, 0xda, 0x84, 0x82, 0x3e, 0x52, 0x8a, 0xff, 0xf6, 0x60, 0x39, 0xdc, 0x40, 0x8b, 0x7f,
	0x0a, 0x21, 0xf9, 0x24, 0xf6, 0xd2, 0xd9, 0x50, 0xd0, 0xe4, 0x98, 0x80, 0xa0, 0xc4, 0x5f, 0xcd,
	0x3d, 0x44, 0x9b, 0x44, 0x8c, 0xab, 0xc5, 0x3b, 0x65, 0xec, 0x7b, 0x2d, 0x31, 0x23, 0x9c, 0xc3,
	0x57, 0x35, 0xfe, 0xa4, 0xf5, 0xff, 0x83, 0x77, 0xb8, 0xe4, 0x15, 0xcc, 0xbb, 0xcc, 0x69, 0x5e,
	0xd8, 0xfc, 0xf1, 0x21, 0x24, 0x6a, 0x76, 0x05, 0x17, 0xd7, 0x68, 0x9d, 0x11, 0x50, 0x36, 0x16,
	0x17, 0x7b, 0x3e, 0x4c, 0x96, 0x62, 0xa4, 0x11, 0x3f, 0x63, 0x2f, 0x61, 0xb1, 0x57, 0x64, 0xd8,
	0x52, 0x8c, 0xcc, 0x99, 0xac, 0x26, 0xe3, 0xf3, 0xb3, 0xb6, 0xdb, 0x76, 0xa7, 0xcd, 0xc9, 0xdd,
	0x86, 0xa2, 0x7b, 0x77, 0x7b, 0x01, 0xf0, 0x06, 0x77, 0xd8, 0xd8, 0x71, 0xd2, 0xea, 0x52, 0xec,
	0x9b, 0x87, 0xc6, 0x83, 0xe1, 0x29, 0x30, 0x26, 0x26, 0xef, 0xe2, 0x48, 0xd1, 0x60, 0x7a, 0xc6,
	0xc4, 0xe4, 0x05, 0x1c, 0x28, 0xfa, 0x7a, 0x4e, 0xff, 0x95, 0xab, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0x0f, 0xe0, 0x0b, 0x66, 0x04, 0x00, 0x00,
}
